import type { LugandaTranslateMode } from "../lib/settings.js";
import { translateListToLuganda, translateToLuganda } from "../speech/gemini.js";
import { numberToLuganda } from "../speech/luganda-numbers.js";

type Row = Record<string, unknown>;

// Only through 10th — an 11th+ item just repeats "ekidako" ("the next
// one"), per the reference given for this feature; a Tuma shopping list
// realistically never runs much past this anyway.
const ORDINALS = [
  "ekisooka", "ekyokubiri", "ekyokusatu", "ekyokuna", "ekyokutaano",
  "ekyomukaaga", "ekyomusaanvu", "ekyomunaana", "ekyomwenda", "ekyokumi",
];
function ordinal(index: number): string {
  return ORDINALS[index] ?? "ekidako";
}

/**
 * Builds the Luganda text read aloud to a rider for one order's shopping
 * list — see ../speech/gemini.ts and ../speech/luganda-numbers.ts.
 *
 * Item names are translated by Gemini — item by item, or the whole list in
 * one request (admin setting, Settings → Luganda list reading) — but every number
 * is generated by our own deterministic converter and spliced straight into
 * the Luganda text; a machine translation of a number can silently change
 * its value (an earlier provider turned "sixteen thousand" into a phrase
 * worth 10x), which is too risky for something read out as a price.
 *
 * A quantity of 1 (a single heap/bunch — tomatoes, onions, the usual way
 * loose vegetables are priced) is read as just "item. price.", with no
 * "each" and no repeated total — there's nothing to multiply. A quantity
 * above 1 (a countable/weighed unit — "2 kilograms of rice") states the
 * unit price ("...buli emu") and the line total ("...awamu") separately.
 */
export async function buildLugandaListNarration(items: Row[], mode: LugandaTranslateMode = "per_item"): Promise<string> {
  // Translated concurrently rather than one at a time — a list of any real
  // size turns this into several sequential translation round-trips, and a
  // single slow one in the chain was enough to trip a platform-level
  // timeout in production (confirmed live: an otherwise-identical retry
  // succeeded in well under half the time a sequential run took).
  const namePhrases = items.map((item) => {
    const quantity = Number(item.quantity) || 1;
    const name = String(item.name);
    return quantity > 1 ? `${quantity} ${name}` : name;
  });
  // "whole_list" asks for everything in one request (a handful of requests
  // saved per list); if the answer doesn't line up it quietly does it item by
  // item instead, so the choice only ever affects cost, never correctness.
  let lugandaNames: string[] | null = null;
  if (mode === "whole_list" && namePhrases.length > 1) {
    lugandaNames = await translateListToLuganda(namePhrases).catch(() => null);
  }
  if (!lugandaNames) lugandaNames = await Promise.all(namePhrases.map((phrase) => translateToLuganda(phrase)));

  const parts: string[] = [];
  let grandTotal = 0;

  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    const quantity = Number(item.quantity) || 1;
    const unitPrice = item.unit_price != null ? Number(item.unit_price) : null;
    let line = `${ordinal(i)}, ${lugandaNames[i]}.`;
    if (unitPrice != null) {
      if (quantity > 1) {
        const lineTotal = quantity * unitPrice;
        grandTotal += lineTotal;
        line += ` Ssiringi ${numberToLuganda(unitPrice)} buli emu. Ssiringi ${numberToLuganda(lineTotal)} awamu.`;
      } else {
        grandTotal += unitPrice;
        line += ` Ssiringi ${numberToLuganda(unitPrice)}.`;
      }
    }
    parts.push(line);
  }

  if (grandTotal > 0) {
    parts.push(`Omugatte gwonna: Ssiringi ${numberToLuganda(grandTotal)}.`);
  }

  return parts.join(" ");
}
