import { translateToLuganda } from "../speech/sunbird.js";
import { numberToLuganda } from "../speech/luganda-numbers.js";

type Row = Record<string, unknown>;

// Only through 10th — an 11th+ item just repeats "ekidako" ("the next
// one"), per the reference given for this feature; a Tuma shopping list
// realistically never runs much past this anyway.
const ORDINALS = [
  "ekisooka", "ekyokubiri", "ekyokusatu", "ekyokuna", "ekyokutaano",
  "ekyomukaaga", "ekyomusaanvu", "ekyomunaana", "ekyomwenda", "ekyokumi",
];
function ordinal(index: number): string {
  return ORDINALS[index] ?? "ekidako";
}

/**
 * Builds the Luganda text read aloud to a rider for one order's shopping
 * list — see ../speech/sunbird.ts and ../speech/luganda-numbers.ts.
 *
 * Item names are translated by Sunbird (short, reliable — confirmed live
 * this session), but every number is generated by our own deterministic
 * converter and spliced straight into the Luganda text; Sunbird's own
 * translation of numbers was confirmed unreliable (it silently produced a
 * phrase worth 10x the real amount for "sixteen thousand"), which is too
 * risky for something read out as a price.
 *
 * A quantity of 1 (a single heap/bunch — tomatoes, onions, the usual way
 * loose vegetables are priced) is read as just "item. price.", with no
 * "each" and no repeated total — there's nothing to multiply. A quantity
 * above 1 (a countable/weighed unit — "2 kilograms of rice") states the
 * unit price ("...buli emu") and the line total ("...awamu") separately.
 */
export async function buildLugandaListNarration(items: Row[]): Promise<string> {
  const parts: string[] = [];
  let grandTotal = 0;

  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    const quantity = Number(item.quantity) || 1;
    const name = String(item.name);
    const namePhrase = quantity > 1 ? `${quantity} ${name}` : name;
    const lugandaName = await translateToLuganda(namePhrase);

    const unitPrice = item.unit_price != null ? Number(item.unit_price) : null;
    let line = `${ordinal(i)}, ${lugandaName}.`;
    if (unitPrice != null) {
      if (quantity > 1) {
        const lineTotal = quantity * unitPrice;
        grandTotal += lineTotal;
        line += ` Ssiringi ${numberToLuganda(unitPrice)} buli emu. Ssiringi ${numberToLuganda(lineTotal)} awamu.`;
      } else {
        grandTotal += unitPrice;
        line += ` Ssiringi ${numberToLuganda(unitPrice)}.`;
      }
    }
    parts.push(line);
  }

  if (grandTotal > 0) {
    parts.push(`Omugatte gwonna: Ssiringi ${numberToLuganda(grandTotal)}.`);
  }

  return parts.join(" ");
}
