"use client";
import type {FoodItemFeedback} from "@peebee/shared";
import {Star,ThumbsUp} from "lucide-react";
import {useCallback,useEffect,useState} from "react";
import {api,errorMessage} from "../lib/api";
export function DishReviews({restaurantId,itemId,isDemo=false}:{restaurantId:string;itemId:string;isDemo?:boolean}){
 const [feedback,setFeedback]=useState<FoodItemFeedback|null>(null),[error,setError]=useState<string|null>(null),[rating,setRating]=useState(0),[comment,setComment]=useState(""),[recommended,setRecommended]=useState(false),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
 const load=useCallback(async()=>{const result=await api.foodItemFeedback(restaurantId,itemId);setFeedback(result);if(result.myReview){setRating(result.myReview.rating);setComment(result.myReview.comment??"");setRecommended(result.myReview.recommended);}},[restaurantId,itemId]);
 useEffect(()=>{if(isDemo)return;void load().catch(err=>setError(errorMessage(err)));},[isDemo,load]);
 async function save(){if(!feedback?.eligibleOrderId)return;setBusy(true);setError(null);try{await api.saveFoodItemReview(restaurantId,itemId,{orderId:feedback.eligibleOrderId,rating,comment,recommended});await load();setSaved(true);}catch(err){setError(errorMessage(err));}finally{setBusy(false);}}
 if(isDemo)return <section className="space-y-2"><h2 className="font-bold">Reviews & recommendations</h2><p className="text-sm text-ink-500">Reviews will appear here when this dish has customer feedback.</p></section>;
 return <section className="space-y-4"><h2 className="text-lg font-bold">Reviews & recommendations</h2>{feedback&&<div className="flex flex-wrap gap-3 text-sm"><span className="flex items-center gap-1"><Star size={16} className="text-gold"/>{feedback.averageRating?.toFixed(1)??"New"} · {feedback.ratingCount} ratings</span><span className="flex items-center gap-1"><ThumbsUp size={16}/>{feedback.recommendCount} recommend</span></div>}{error&&<p role="alert" className="text-sm">{error}<button type="button" onClick={()=>void load().then(()=>setError(null)).catch(err=>setError(errorMessage(err)))} className="ml-2 min-h-11 font-bold text-gold">Retry</button></p>}
 {!feedback&&!error&&<p role="status" className="text-sm text-ink-500">Loading reviews…</p>}
 {feedback&&!feedback.available&&<p className="text-sm text-ink-500">Dish reviews are being enabled. Please check again shortly.</p>}
 {feedback?.available&&!feedback.eligibleOrderId&&<p className="text-sm text-ink-500">Reviews come from verified purchases. You can review this dish after receiving an order containing it.</p>}
 {feedback?.eligibleOrderId&&<div className="space-y-3 rounded-2xl border border-[var(--border-faint)] p-4"><h3 className="font-bold">{feedback.myReview?"Update your review":"How was your dish?"}</h3><div role="radiogroup" aria-label="Your rating" className="flex gap-2">{[1,2,3,4,5].map(value=><button type="button" role="radio" aria-checked={rating===value} aria-label={`${value} star${value===1?"":"s"}`} key={value} onClick={()=>{setRating(value);setSaved(false);}} disabled={busy} className="flex h-11 w-11 items-center justify-center rounded-full text-gold"><Star size={24} fill={rating>=value?"currentColor":"none"}/></button>)}</div><textarea aria-label="Review comment" placeholder="What did you enjoy?" maxLength={2000} value={comment} disabled={busy} onChange={event=>{setComment(event.target.value);setSaved(false);}} className="min-h-24 w-full rounded-2xl border border-[var(--border-faint)] p-3 text-sm"/><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={recommended} disabled={busy} onChange={event=>{setRecommended(event.target.checked);setSaved(false);}}/>I recommend this dish</label><p className="text-xs text-ink-500">Your first name appears with your review. You can update your review later.</p><button type="button" disabled={busy||rating===0} onClick={()=>void save()} className="min-h-12 w-full rounded-full bg-gold font-bold text-ink-gold disabled:opacity-50">{busy?"Saving…":feedback.myReview?"Update review":"Post review"}</button>{saved&&<p role="status" className="text-sm">Your review is saved.</p>}</div>}
 {feedback?.available&&!feedback.reviews.length&&<p className="text-sm text-ink-500">No reviews yet.</p>}
 {feedback?.reviews.map(review=><article key={review.id} className="space-y-2 rounded-2xl border border-[var(--border-faint)] p-4"><div className="flex items-center justify-between"><strong className="text-sm">{review.authorName}</strong><span className="flex items-center gap-1 text-xs"><Star size={13} className="text-gold"/>{review.rating}</span></div>{review.comment&&<p className="whitespace-pre-wrap break-words text-sm">{review.comment}</p>}{review.recommended&&<p className="flex items-center gap-1 text-xs text-ink-500"><ThumbsUp size={12}/>Recommends this dish</p>}<p className="text-xs text-ink-500">Verified purchase</p></article>)}{feedback&&feedback.ratingCount>feedback.reviews.length&&<p className="text-xs text-ink-500">Showing the latest {feedback.reviews.length} reviews.</p>}
 </section>;
}
