"use client";
import { useCallback,useEffect,useState } from 'react';
import { Select } from '@peebee/shared/select';
import type { OnboardingSettings,SalesAgent } from '@peebee/shared';
import { useAuth } from '../../lib/auth-context';
import { getStoredToken } from '../../lib/api';
const base=process.env.NEXT_PUBLIC_API_URL??'http://localhost:10000';
async function api<T>(path:string,options:RequestInit={}):Promise<T>{const res=await fetch(`${base}/v1/admin/onboarding${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${getStoredToken()}`},cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.message??'Could not complete this request.');return data as T;}
export default function Onboarding(){
  const {user}=useAuth();const [settings,setSettings]=useState<OnboardingSettings|null>(null),[agents,setAgents]=useState<SalesAgent[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[waToken,setWaToken]=useState(''),[smsKey,setSmsKey]=useState(''),[clearWa,setClearWa]=useState(false),[clearSms,setClearSms]=useState(false),[existingEmail,setExistingEmail]=useState('');
  const load=useCallback(async()=>{const [policy,list]=await Promise.all([api<OnboardingSettings>('/settings'),api<{agents:SalesAgent[]}>('/agents')]);setSettings(policy);setAgents(list.agents);},[]);
  useEffect(()=>{if(user?.adminRole==='super_admin')load().catch(e=>setError(e.message));},[user?.adminRole,load]);
  async function action(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();await load();}catch(e){setError(e instanceof Error?e.message:'Request failed.');}finally{setBusy(false);}}
  async function save(e:React.FormEvent){e.preventDefault();await action(async()=>{await api('/settings',{method:'PUT',body:JSON.stringify({...settings,whatsappToken:waToken,smsKey,clearWhatsappToken:clearWa,clearSmsKey:clearSms})});setWaToken('');setSmsKey('');setClearWa(false);setClearSms(false);setNotice('Onboarding settings saved.');});}
  async function invite(e:React.FormEvent){e.preventDefault();await action(async()=>{const result=await api<{delivery:{sent:boolean}}>('/agents',{method:'POST',body:JSON.stringify({name,email,phone,consent:true})});setName('');setEmail('');setPhone('');setNotice(result.delivery.sent?'Agent invited. They can activate their own account.':'Agent saved. Configure a messaging channel, then resend the activation.');});}
  function patch<K extends keyof OnboardingSettings>(key:K,value:OnboardingSettings[K]){setSettings(old=>old?{...old,[key]:value}:old);}
  const field=(label:string,value:string,change:(s:string)=>void,type='text')=><label className="block text-sm font-semibold">{label}<input type={type} value={value} onChange={e=>change(e.target.value)} className="mt-2 w-full rounded-xl border border-[var(--border-faint)] px-3 py-2.5"/></label>;
  if(user?.adminRole!=='super_admin')return <p className="p-6 text-sm">Only a Super Admin can manage agent access and onboarding settings.</p>;
  return <section className="space-y-6 px-4 py-6"><div><p className="text-xs font-bold uppercase tracking-wider text-ink-500">Sales onboarding</p><h1 className="mt-2 text-2xl font-black">Agents & activation</h1><a className="mt-3 inline-block text-sm font-bold text-gold" href="https://sales.peebee.online">Open the sales app →</a></div>
    {error&&<p role="alert" className="card p-4 text-sm">{error}</p>}{notice&&<p role="status" className="card p-4 text-sm">{notice}</p>}
    <section className="card space-y-4 p-5"><h2 className="text-lg font-black">Invite a sales agent</h2><p className="text-xs text-ink-500">Agents can onboard customers, riders, restaurants and merchants. They see their own registrations and do not get administrator access.</p><form onSubmit={invite} className="space-y-4"><label className="block text-sm">Full name<input required value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl border border-[var(--border-faint)] px-3 py-2.5"/></label><label className="block text-sm">Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-[var(--border-faint)] px-3 py-2.5"/></label>{field('Phone (optional)',phone,setPhone,'tel')}<button disabled={busy} className="rounded-full bg-gold px-5 py-3 text-sm font-bold text-ink-gold">Invite agent</button></form><details className="border-t border-[var(--border-faint)] pt-4"><summary className="cursor-pointer text-sm font-semibold">Give an existing user agent access</summary><form onSubmit={e=>{e.preventDefault();void action(async()=>{await api('/agents/existing',{method:'POST',body:JSON.stringify({email:existingEmail})});setExistingEmail('');setNotice('Agent access enabled for the existing account.');});}} className="mt-4 space-y-3">{field('Existing account email',existingEmail,setExistingEmail,'email')}<button disabled={busy} className="rounded-full border border-[var(--border-faint)] px-4 py-2 text-sm font-bold">Enable agent access</button></form></details></section>
    <section className="card space-y-3 p-5"><h2 className="text-lg font-black">Sales agents</h2>{!agents.length?<p className="text-sm text-ink-500">No agents invited yet.</p>:agents.map(agent=><div key={agent.user_id} className="border-t border-[var(--border-faint)] py-3"><p className="font-semibold">{agent.name}</p><p className="text-xs text-ink-500">{agent.email} · {agent.enabled?'Access enabled':'Access disabled'}</p><div className="mt-3 flex flex-wrap gap-3"><button disabled={busy} onClick={()=>action(async()=>{await api(`/agents/${agent.user_id}`,{method:'POST',body:JSON.stringify({enabled:!agent.enabled})});})} className="rounded-full border border-[var(--border-faint)] px-3 py-2 text-xs font-bold">{agent.enabled?'Disable access':'Enable access'}</button>{!agent.activated_at&&agent.enabled===1&&<button disabled={busy} onClick={()=>action(async()=>{const r=await api<{delivery:{sent:boolean}}>(`/agents/${agent.user_id}/resend`,{method:'POST'});setNotice(r.delivery.sent?'Agent activation sent.':'Messaging provider could not send activation.');})} className="rounded-full border border-[var(--border-faint)] px-3 py-2 text-xs font-bold">Resend activation</button>}</div></div>)}</section>
    {settings&&<form onSubmit={save} className="card space-y-5 p-5"><h2 className="text-lg font-black">Onboarding policy</h2><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={settings.enabled} onChange={e=>patch('enabled',e.target.checked)}/>Allow new onboarding and activation messages</label><label className="block text-sm">Activation link expiry (hours)<input type="number" min={1} max={720} required value={settings.activationHours} onChange={e=>patch('activationHours',Number(e.target.value))} className="mt-2 w-full rounded-xl border border-[var(--border-faint)] px-3 py-2.5"/></label><label className="block text-sm">Minimum time between messages (seconds)<input type="number" min={30} max={86400} required value={settings.resendSeconds} onChange={e=>patch('resendSeconds',Number(e.target.value))} className="mt-2 w-full rounded-xl border border-[var(--border-faint)] px-3 py-2.5"/></label><label className="block text-sm">Automatic retry limit<input type="number" min={1} max={20} required value={settings.maxAttempts} onChange={e=>patch('maxAttempts',Number(e.target.value))} className="mt-2 w-full rounded-xl border border-[var(--border-faint)] px-3 py-2.5"/></label><fieldset className="space-y-3"><legend className="mb-2 text-sm font-semibold">Enabled activation channels</legend>{(['email','sms','whatsapp'] as const).map(channel=><label key={channel} className="flex items-center gap-3 text-sm"><input type="checkbox" checked={settings.channels.includes(channel)} onChange={e=>patch('channels',e.target.checked?[...settings.channels,channel]:settings.channels.filter(c=>c!==channel))}/>{channel==='whatsapp'?'WhatsApp':channel==='sms'?'SMS':'Email'} · {settings.providers[channel]?'Configured':'Not configured'}</label>)}</fieldset><p className="text-xs text-ink-500">The chosen channel is tried first, then enabled alternatives. Email uses the keys in Settings → Email API keys.</p>
    <h3 className="border-t border-[var(--border-faint)] pt-5 font-bold">SMS · Africa’s Talking</h3>{field('Username',settings.smsUsername,s=>patch('smsUsername',s))}{field(settings.smsKeySet?'API key (saved; leave blank to keep)':'API key',smsKey,setSmsKey,'password')}<label className="flex items-center gap-3 text-xs"><input type="checkbox" checked={clearSms} onChange={e=>setClearSms(e.target.checked)}/>Clear the saved SMS key</label>
    <h3 className="border-t border-[var(--border-faint)] pt-5 font-bold">WhatsApp · Meta Business</h3><p className="text-xs text-ink-500">Use an approved utility template with two body variables: the recipient’s name and their activation link.</p>{field('Phone number ID',settings.whatsappPhoneId,s=>patch('whatsappPhoneId',s))}{field('Approved template name',settings.whatsappTemplate,s=>patch('whatsappTemplate',s))}{field('Template language',settings.whatsappLanguage,s=>patch('whatsappLanguage',s))}{field('API version',settings.whatsappVersion,s=>patch('whatsappVersion',s))}{field(settings.whatsappTokenSet?'Access token (saved; leave blank to keep)':'Access token',waToken,setWaToken,'password')}<label className="flex items-center gap-3 text-xs"><input type="checkbox" checked={clearWa} onChange={e=>setClearWa(e.target.checked)}/>Clear the saved WhatsApp token</label><button disabled={busy} className="w-full rounded-full bg-gold px-4 py-3 font-bold text-ink-gold">{busy?'Saving…':'Save onboarding settings'}</button></form>}
  </section>;
}
