"use client";
import { useCallback,useEffect,useRef,useState } from 'react';
import { Bike,Store,UserRound,Utensils,Check,ArrowRight,LocateFixed,LogOut,Plus,RefreshCw } from 'lucide-react';
import { Select } from '@peebee/shared/select';
import { ONBOARDING_TYPES,type OnboardingType,type OnboardingRecord,type ActivationChannel } from '@peebee/shared';
import { BrandLogo } from '../components/BrandLogo';
import { request,TOKEN_KEY } from '../lib/api';
const labels:Record<OnboardingType,string>={customer:'Customer',rider:'Rider',restaurant:'Restaurant',merchant:'Merchant'};
const icons={customer:UserRound,rider:Bike,restaurant:Utensils,merchant:Store};
type Draft={profile:Record<string,string|number>;files:Record<string,File>};
const emptyDrafts=():Record<OnboardingType,Draft>=>({customer:{profile:{},files:{}},rider:{profile:{},files:{}},restaurant:{profile:{},files:{}},merchant:{profile:{},files:{}}});
const riderFields=[['firstName','First name'],['lastName','Last name'],['vehicleInfo','Motorcycle registration'],['stageName','Stage name'],['stageAddress','Stage address'],['homeAddress','Home address'],['stageChairmanName','Stage chairman'],['stageChairmanContact','Chairman phone'],['emergencyContactName','Emergency contact'],['emergencyContactPhone','Emergency contact phone'],['momoMsisdn','Mobile money number']] as const;
export default function Sales(){
  const [me,setMe]=useState<{user:{name:string};superAdmin:boolean}|null>(null),[records,setRecords]=useState<OnboardingRecord[]>([]);
  const [type,setType]=useState<OnboardingType>('customer'),[drafts,setDrafts]=useState(emptyDrafts),[name,setName]=useState(''),[phone,setPhone]=useState(''),[email,setEmail]=useState(''),[channel,setChannel]=useState<ActivationChannel>('auto');
  const [consent,setConsent]=useState(false),[defer,setDefer]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState<'new'|'records'>('new');
  const [categories,setCategories]=useState<Array<{id:string;name:string}>>([]),[retry,setRetry]=useState('');
  const requestId=useRef('');const draft=drafts[type];
  const load=useCallback(async()=>{const data=await request<{records:OnboardingRecord[]}>('/sales/onboarding');setRecords(data.records);},[]);
  useEffect(()=>{let alive=true;requestId.current=crypto.randomUUID();if(!localStorage.getItem(TOKEN_KEY)){window.location.replace('/login');return;}
    Promise.all([request<{user:{name:string};superAdmin:boolean}>('/sales/me'),request<{categories:Array<{id:string;name:string}>}>('/sales/categories')]).then(([session,data])=>{if(alive){setMe(session);setCategories(data.categories);return load();}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[load]);
  function profile(key:string,value:string|number){setDrafts(old=>({...old,[type]:{...old[type],profile:{...old[type].profile,[key]:value}}}));}
  function file(key:string,value:File|undefined){setDrafts(old=>{const files={...old[type].files};if(value)files[key]=value;else delete files[key];return {...old,[type]:{...old[type],files}};});}
  async function locate(){setError('');if(!navigator.geolocation){setError('Location is unavailable on this device. Enter the coordinates below.');return;}
    navigator.geolocation.getCurrentPosition(position=>{setDrafts(old=>({...old,[type]:{...old[type],profile:{...old[type].profile,lat:position.coords.latitude,lng:position.coords.longitude}}}));},()=>setError('Could not get this location. Enter the coordinates below.'),{enableHighAccuracy:true,timeout:15000});}
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');
    const selectedType=type;
    try{const form=new FormData();const cleanProfile=Object.fromEntries(Object.entries(draft.profile).filter(([,value])=>value!==''));
      form.set('data',JSON.stringify({requestId:requestId.current,accountType:selectedType,name,phone,email,preferredChannel:channel,consent,profile:cleanProfile}));
      for(const [key,value]of Object.entries(draft.files))form.set(key,value);
      const result=await request<{delivery?:{sent:boolean;channel?:string};replayed?:boolean}>('/sales/onboarding',{method:'POST',body:form});
      setNotice(result.delivery?.sent?`${labels[selectedType]} registered. Activation sent by ${result.delivery.channel}.`:result.replayed?'This account was already saved.':'Account saved. Activation could not be sent yet; ask Admin to check the messaging provider, then retry from Records.');
      setName('');setPhone('');setEmail('');setConsent(false);setDefer(false);setDrafts(emptyDrafts());requestId.current=crypto.randomUUID();setTab('records');await load();
    }catch(e){setError(e instanceof Error?e.message:'Could not save this account.');}finally{setBusy(false);}}
  async function resend(id:string){setRetry(id);setError('');setNotice('');try{const res=await request<{delivery:{sent:boolean;channel?:string}}>(`/sales/onboarding/${id}/resend`,{method:'POST'});setNotice(res.delivery.sent?'Activation message sent.':'The account is saved, but the messaging provider could not send activation.');await load();}catch(e){setError(e instanceof Error?e.message:'Could not send activation.');}finally{setRetry('');}}
  function field(key:string,label:string,required=false,kind='text'){return <label key={key} className="block text-sm font-semibold">{label}<input type={kind} step={kind==='number'?'any':undefined} required={required&&!defer} value={draft.profile[key]??''} onChange={e=>profile(key,kind==='number'&&e.target.value!==''?Number(e.target.value):e.target.value)} className="sales-input mt-2"/></label>;}
  function upload(key:string,label:string,required=false,photoOnly=false){return <label className="block text-sm font-semibold">{label}<input key={`${type}-${key}-${requestId.current}`} type="file" accept={photoOnly?'image/jpeg,image/png,image/webp':'image/jpeg,image/png,image/webp,application/pdf'} required={required&&!defer&&!draft.files[key]} onChange={e=>file(key,e.target.files?.[0])} className="sales-input mt-2 text-xs"/><span className="mt-1 block text-xs font-normal text-ink-500">{photoOnly?'JPG, PNG or WebP, up to 4 MB':'JPG, PNG, WebP or PDF, up to 8 MB'}{draft.files[key]?` · ${draft.files[key].name}`:''}</span></label>;}
  const activated=records.filter(r=>r.activated_at).length;
  return <div className="min-h-dvh"><header className="border-b border-[var(--border-faint)] bg-[rgb(var(--surface))]"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><div className="flex items-center gap-4"><BrandLogo/><span className="border-l border-[var(--border-faint)] pl-4 text-sm font-semibold text-ink-500">Sales</span></div><div className="flex items-center gap-3"><span className="hidden text-sm text-ink-500 sm:block">{me?.user.name}</span><button aria-label="Sign out" onClick={()=>{localStorage.removeItem(TOKEN_KEY);window.location.replace('/login');}} className="rounded-full p-2"><LogOut size={18}/></button></div></div></header>
    <main className="mx-auto max-w-6xl px-5 py-8"><div className="mb-7 flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-widest text-ink-500">Grow the Peebee community</p><h1 className="mt-2 text-3xl font-black">Onboard with confidence.</h1><p className="mt-2 text-sm text-ink-500">Capture the details once. We’ll handle account activation.</p></div><div className="flex gap-5"><div><strong className="text-2xl">{records.length}</strong><p className="text-xs text-ink-500">Recent registrations</p></div><div><strong className="text-2xl">{activated}</strong><p className="text-xs text-ink-500">Activated</p></div></div></div>
    <nav aria-label="Onboarding sections" className="mb-6 flex gap-2"><button onClick={()=>setTab('new')} className={`sales-tab ${tab==='new'?'sales-tab-active':''}`}><Plus size={17}/>New registration</button><button onClick={()=>setTab('records')} className={`sales-tab ${tab==='records'?'sales-tab-active':''}`}>Records</button>{me?.superAdmin&&<a href="https://admin.peebee.online/onboarding" className="sales-tab">Manage agents</a>}</nav>
    {notice&&<p role="status" className="mb-5 flex items-center gap-3 rounded-2xl border border-[var(--border-faint)] bg-[rgb(var(--surface))] p-4 text-sm"><Check size={20}/>{notice}</p>}{error&&<p role="alert" className="mb-5 rounded-2xl border border-[var(--border-faint)] p-4 text-sm">{error}</p>}
    {!me&&!error?<p role="status">Loading your workspace…</p>:tab==='new'?<div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_280px]"><div><section className="mb-6"><h2 className="mb-3 text-sm font-bold">Who are you onboarding?</h2><div role="group" aria-label="Active onboarding profile" className="grid grid-cols-2 gap-3 sm:grid-cols-4">{ONBOARDING_TYPES.map(value=>{const Icon=icons[value];return <button disabled={busy} type="button" key={value} aria-pressed={type===value} onClick={()=>{setType(value);setError('');}} className={`flex min-h-24 flex-col items-start gap-3 rounded-2xl border px-4 py-4 text-sm font-bold ${type===value?'border-gold bg-gold text-ink-gold':'border-[var(--border-faint)] bg-[rgb(var(--surface))]'}`}><Icon size={23}/>{labels[value]}</button>;})}</div></section>
    <form onSubmit={submit} className="space-y-6"><fieldset disabled={busy} className="home-card space-y-5"><legend className="sr-only">Contact details</legend><div><p className="text-xs font-bold uppercase tracking-wider text-ink-500">01 · {labels[type]} profile</p><h2 className="mt-1 text-xl font-black">Contact details</h2></div><label className="block text-sm font-semibold">Full name<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)} autoComplete="off" className="sales-input mt-2"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold">Phone<input type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+256…" autoComplete="off" className="sales-input mt-2"/></label><label className="block text-sm font-semibold">Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="off" className="sales-input mt-2"/></label></div><p className="text-xs text-ink-500">Add at least one contact. Their activation message will go here.</p><label className="block text-sm font-semibold">Activation channel<Select value={channel} onValueChange={value=>setChannel(value as ActivationChannel)} className="mt-2"><option value="auto">Best available channel</option><option value="email">Email</option><option value="whatsapp">WhatsApp</option><option value="sms">SMS</option></Select></label></fieldset>
    {type!=='customer'&&<fieldset disabled={busy} className="home-card space-y-5"><legend className="sr-only">{labels[type]} details</legend><div><p className="text-xs font-bold uppercase tracking-wider text-ink-500">02 · Details</p><h2 className="mt-1 text-xl font-black">{type==='rider'?'Rider profile':'Business profile'}</h2></div><div className="grid gap-4 sm:grid-cols-2">{type==='rider'?riderFields.map(([key,label])=>field(key,label,key!=='momoMsisdn',key.toLowerCase().includes('phone')||key.includes('Contact')&&key!=='emergencyContactName'?'tel':'text')):<>{field('businessName','Business name',true)}{type==='merchant'?<>{field('legalName','Legal business name',true)}{field('outletName','Outlet name',true)}<label className="block text-sm font-semibold">Category<Select required value={String(draft.profile.categoryId??'')} onValueChange={value=>profile('categoryId',value)} className="mt-2"><option value="">Choose category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></label></>:field('cuisine','Cuisine')}{field('address','Business address',true)}{type==='restaurant'&&<>{field('openTime','Opens at',false,'time')}{field('closeTime','Closes at',false,'time')}</>}</>}</div>
    <div className="rounded-2xl border border-[var(--border-faint)] p-4"><div className="flex items-center justify-between gap-3"><div><h3 className="text-sm font-bold">{type==='rider'?'Stage location':'Business location'}</h3><p className="text-xs text-ink-500">Capture the location while you’re there.</p></div><button type="button" onClick={locate} className="sales-tab"><LocateFixed size={17}/>Use this location</button></div><div className="mt-4 grid grid-cols-2 gap-4">{field('lat','Latitude',true,'number')}{field('lng','Longitude',true,'number')}</div></div>
    {type==='rider'?<div className="grid gap-4 sm:grid-cols-2">{upload('riderId','National ID',true)}{upload('photo','Face photo',true,true)}</div>:type==='merchant'?<div className="grid gap-4 sm:grid-cols-2">{upload('ownerId','Owner ID')}{upload('businessDocument','Business registration')}</div>:null}
    {type==='rider'&&<label className="flex items-start gap-3 text-sm"><input type="checkbox" checked={defer} onChange={e=>setDefer(e.target.checked)} className="mt-1"/><span>Some details need to be completed later.<span className="block text-xs text-ink-500">The rider keeps everything captured here and only completes what’s missing.</span></span></label>}</fieldset>}
    <fieldset disabled={busy} className="home-card space-y-4"><h2 className="text-lg font-black">Ready to register this {labels[type].toLowerCase()}?</h2><label className="flex items-start gap-3 text-sm"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1"/><span>The person has agreed to create their Peebee account and receive an activation message.</span></label><button disabled={busy||!me} className="sales-primary w-full">{busy?'Saving and sending…':`Register ${labels[type].toLowerCase()} & send activation`}<ArrowRight size={18}/></button></fieldset></form></div>
    <aside className="home-card space-y-5 lg:sticky lg:top-6"><p className="text-xs font-bold uppercase tracking-wider text-ink-500">Active profile</p><div className="flex items-center gap-3">{(()=>{const Icon=icons[type];return <Icon size={25}/>;})()}<strong className="text-xl">{labels[type]}</strong></div><p className="text-sm text-ink-500">This is the account type that will be registered.</p><ol className="space-y-4 text-sm"><li>1. Capture their contact and profile.</li><li>2. Save the account to Peebee.</li><li>3. They activate it and choose a password.</li></ol><p className="border-t border-[var(--border-faint)] pt-4 text-xs text-ink-500">{type==='customer'?'No second signup is needed.':'Existing verification and approval checks still apply. Captured details and documents are retained.'}</p></aside></div>:<section className="home-card"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-black">Your recent registrations</h2><button aria-label="Refresh records" className="sales-tab" onClick={()=>load().catch(e=>setError(e.message))}><RefreshCw size={17}/></button></div>{!records.length?<p className="py-8 text-center text-sm text-ink-500">Your first registration will appear here.</p>:<ul className="divide-y divide-[var(--border-faint)]">{records.map(record=><li key={record.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="font-bold">{record.name}</p><p className="text-xs text-ink-500">{labels[record.account_type as OnboardingType]} · {record.email??record.phone}</p><p className="mt-1 text-xs">{record.activated_at?'Activated':record.delivery_status==='sent'?`Activation sent · ${record.delivery_channel}`:record.delivery_status==='sending'?'Sending activation…':'Awaiting activation · message needs attention'}</p></div>{!record.activated_at&&<button onClick={()=>resend(record.id)} disabled={!!retry} className="sales-tab">{retry===record.id?'Sending…':'Resend activation'}</button>}</li>)}</ul>}</section>}
    </main></div>;
}
