"use client";
import {COLOUR_SCENES,DEFAULT_COLOUR_SCENE,type ColourScene,type Restaurant} from "@peebee/shared";
import {useEffect,useState} from "react";
import {api,errorMessage} from "../lib/api";
export function BusinessStyleEditor({restaurant,onSaved}:{restaurant:Restaurant;onSaved:()=>Promise<void>}){
 const [scene,setScene]=useState<ColourScene>(restaurant.theme_scene??DEFAULT_COLOUR_SCENE),[mode,setMode]=useState<"auto"|"light"|"dark">(restaurant.theme_mode??"auto"),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null);
 useEffect(()=>{setScene(restaurant.theme_scene??DEFAULT_COLOUR_SCENE);setMode(restaurant.theme_mode??"auto");},[restaurant.theme_scene,restaurant.theme_mode]);
 async function save(){setBusy(true);setMessage(null);try{await api.updateRestaurant({themeScene:scene,themeMode:mode});await onSaved();setMessage("Business theme saved. Customers see this theme while browsing your food.");}catch(err){setMessage(errorMessage(err));}finally{setBusy(false);}}
 return <section className="home-card space-y-4"><h2 className="font-bold">Business theme</h2><p className="text-sm text-ink-500">Choose the colours customers see in your storefront and dish pages.</p><div className="grid grid-cols-2 gap-2" role="group" aria-label="Business colour theme">{COLOUR_SCENES.map(option=><button type="button" key={option.id} aria-pressed={scene===option.id} disabled={busy} onClick={()=>setScene(option.id)} className={`scene-choice ${scene===option.id?"scene-choice-selected":""}`}><span className="scene-swatches" aria-hidden>{option.colours.map(colour=><span key={colour} style={{backgroundColor:colour}}/>)}</span><span className="scene-name">{option.name}</span></button>)}</div><div className="flex gap-2" role="group" aria-label="Business appearance">{(["auto","light","dark"] as const).map(value=><button type="button" key={value} aria-pressed={mode===value} disabled={busy} onClick={()=>setMode(value)} className={`min-h-11 flex-1 rounded-full border border-[var(--border-faint)] text-sm font-bold ${mode===value?"bg-gold text-ink-gold":""}`}>{value==="auto"?"Auto":value==="light"?"Light":"Dark"}</button>)}</div><button type="button" disabled={busy} onClick={()=>void save()} className="min-h-12 w-full rounded-full bg-gold font-bold text-ink-gold disabled:opacity-60">{busy?"Saving…":"Save business theme"}</button>{message&&<p role="status" className="text-sm">{message}</p>}</section>;
}
