"use client";
import type {Restaurant} from "@peebee/shared";
import {Store} from "lucide-react";
import {useEffect,useState} from "react";
import {api,errorMessage} from "../lib/api";
export function LogoEditor({restaurant,onSaved}:{restaurant:Restaurant;onSaved:()=>Promise<void>}){
 const [file,setFile]=useState<File|null>(null),[image,setImage]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null);
 useEffect(()=>{let disposed=false,url:string|undefined;if(file){url=URL.createObjectURL(file);setImage(url);}else if(restaurant.logo_key)api.restaurantLogoBlob(restaurant.id,restaurant.logo_key).then(blob=>{if(disposed)return;url=URL.createObjectURL(blob);setImage(url);}).catch(()=>{if(!disposed)setImage(null);});else setImage(null);return()=>{disposed=true;if(url)URL.revokeObjectURL(url);};},[file,restaurant.id,restaurant.logo_key]);
 async function save(){if(!file)return;setBusy(true);setMessage(null);try{await api.uploadRestaurantLogo(file);await onSaved();setFile(null);setMessage("Logo saved.");}catch(err){setMessage(errorMessage(err));}finally{setBusy(false);}}
 return <section className="home-card space-y-4"><h2 className="font-bold">Business logo</h2><p className="text-sm text-ink-500">Your logo is separate from your cover photo. A transparent PNG works best.</p><div className="mx-auto flex h-24 w-24 items-center justify-center overflow-hidden rounded-2xl bg-[rgb(var(--surface-muted))]">{image?<img src={image} alt={`${restaurant.name} logo`} className="h-full w-full object-contain"/>:<Store size={32}/>}</div><label className="flex min-h-12 cursor-pointer items-center justify-center rounded-full border border-[var(--border-faint)] font-bold focus-within:ring-2 focus-within:ring-gold">Choose logo<input type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" disabled={busy} onChange={event=>{const chosen=event.target.files?.[0];event.target.value="";setMessage(null);if(!chosen)return;if(!["image/png","image/jpeg","image/webp"].includes(chosen.type)||!chosen.size||chosen.size>4*1024*1024){setMessage("Choose a JPG, PNG or WebP image under 4 MB.");return;}setFile(chosen);}}/></label>{file&&<div className="flex gap-2"><button type="button" disabled={busy} onClick={()=>setFile(null)} className="min-h-12 flex-1 rounded-full border border-[var(--border-faint)] font-bold">Cancel</button><button type="button" disabled={busy} onClick={()=>void save()} className="min-h-12 flex-1 rounded-full bg-gold font-bold text-ink-gold">{busy?"Saving…":"Save logo"}</button></div>}{message&&<p role="status" className="text-sm">{message}</p>}</section>;
}
