"use client";
import Link from 'next/link';
import {useState} from 'react';
import {BrandLogo} from '../../components/BrandLogo';
import {request} from '../../lib/api';
import {finishSignIn} from '../../lib/access';
export default function ForgotPassword(){
  const [step,setStep]=useState<'request'|'confirm'>('request'),[identifier,setIdentifier]=useState(''),[code,setCode]=useState(''),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[target,setTarget]=useState(''),[devCode,setDevCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function submit(e:React.FormEvent){e.preventDefault();setError('');if(step==='confirm'&&password!==confirmation){setError('The passwords do not match.');return;}setBusy(true);
    try{if(step==='request'){const r=await request<{target?:string;devCode?:string}>('/auth/password/reset/request',{method:'POST',body:JSON.stringify({identifier:identifier.trim()})});setTarget(r.target??'your account contact');setDevCode(r.devCode??'');setStep('confirm');}else{const r=await request<{token:string}>('/auth/password/reset/confirm',{method:'POST',body:JSON.stringify({identifier:identifier.trim(),code,newPassword:password})});await finishSignIn(r.token);}}
    catch(e){setError(e instanceof Error?e.message:'Could not reset your password.');}finally{setBusy(false);}
  }
  return <main className="mx-auto flex min-h-dvh max-w-md flex-col justify-center px-6 py-10"><BrandLogo className="justify-center"/><h1 className="mt-8 text-2xl font-black">Recover your account</h1><p className="mt-2 text-sm text-ink-500">{step==='request'?'Enter the phone or email on your Peebee account. If an account matches, we will send a recovery code.':`Enter the code sent to ${target} and choose a new password.`}</p><form onSubmit={submit} className="mt-6 space-y-5"><fieldset disabled={busy} className="space-y-5">{step==='request'?<label className="block text-sm font-semibold">Phone or email<input required autoComplete="username" maxLength={160} value={identifier} onChange={e=>setIdentifier(e.target.value)} className="sales-input mt-2"/></label>:<><label className="block text-sm font-semibold">6-digit recovery code<input required autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} className="sales-input mt-2"/></label><label className="block text-sm font-semibold">New password<input required type="password" autoComplete="new-password" minLength={10} maxLength={100} value={password} onChange={e=>setPassword(e.target.value)} className="sales-input mt-2"/></label><label className="block text-sm font-semibold">Confirm password<input required type="password" autoComplete="new-password" minLength={10} maxLength={100} value={confirmation} onChange={e=>setConfirmation(e.target.value)} className="sales-input mt-2"/></label></>}{devCode&&process.env.NODE_ENV!=='production'&&<p className="text-sm">Development code: {devCode}</p>}{error&&<p role="alert" className="text-sm">{error}</p>}<button disabled={busy} className="sales-primary w-full">{busy?'Please wait…':step==='request'?'Send recovery code':'Reset password'}</button>{step==='confirm'&&<button type="button" onClick={()=>{setStep('request');setCode('');setError('');}} className="w-full text-sm font-semibold text-gold">Resend code or use another contact</button>}</fieldset></form><p className="mt-5 text-xs text-ink-500">Account recovery keeps your existing admin approval status.</p><Link href="/login" className="mt-5 text-center text-sm font-semibold text-gold">Back to sign in</Link></main>;
}
